

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setGeometry(QtCore.QRect(570, 0, 221, 561))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 44, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 170, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 44, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 170, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 170, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 170, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea.setPalette(palette)
        self.scrollArea.setMouseTracking(False)
        self.scrollArea.setTabletTracking(False)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 219, 559))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 201, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 53, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 53, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lineEdit.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setFrame(False)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.buttonAccuracy = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.buttonAccuracy.setGeometry(QtCore.QRect(100, 440, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.buttonAccuracy.setFont(font)
        self.buttonAccuracy.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonAccuracy.setObjectName("buttonAccuracy")
        self.buttonLoss = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.buttonLoss.setGeometry(QtCore.QRect(10, 440, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.buttonLoss.setFont(font)
        self.buttonLoss.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonLoss.setObjectName("buttonLoss")
        self.comboBoxSinif = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxSinif.setGeometry(QtCore.QRect(10, 50, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxSinif.setFont(font)
        self.comboBoxSinif.setObjectName("comboBoxSinif")
        self.comboBoxSinif.addItem("")
        self.comboBoxSinif.addItem("")
        self.comboBoxSinif.addItem("")
        self.comboBoxSinif.addItem("")
        self.comboBoxModelSec = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxModelSec.setGeometry(QtCore.QRect(10, 220, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxModelSec.setFont(font)
        self.comboBoxModelSec.setObjectName("comboBoxModelSec")
        self.comboBoxModelSec.addItem("")
        self.comboBoxModelSec.addItem("")
        self.comboBoxModelSec.addItem("")
        self.comboBoxModelSec.addItem("")
        self.comboBoxModelSec.addItem("")
        self.comboBoxKFold = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxKFold.setGeometry(QtCore.QRect(10, 130, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxKFold.setFont(font)
        self.comboBoxKFold.setObjectName("comboBoxKFold")
        self.comboBoxKFold.addItem("")
        self.comboBoxKFold.addItem("")
        self.comboBoxKFold.addItem("")
        self.comboBoxKFold.addItem("")
        self.buttonSinifCalistir = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.buttonSinifCalistir.setGeometry(QtCore.QRect(10, 90, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.buttonSinifCalistir.setFont(font)
        self.buttonSinifCalistir.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonSinifCalistir.setObjectName("buttonSinifCalistir")
        self.buttonModelEgit = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.buttonModelEgit.setGeometry(QtCore.QRect(10, 360, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.buttonModelEgit.setFont(font)
        self.buttonModelEgit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonModelEgit.setObjectName("buttonModelEgit")
        self.buttonKFoldUygula = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.buttonKFoldUygula.setGeometry(QtCore.QRect(10, 170, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.buttonKFoldUygula.setFont(font)
        self.buttonKFoldUygula.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonKFoldUygula.setObjectName("buttonKFoldUygula")
        self.buttonVeriCokla = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.buttonVeriCokla.setGeometry(QtCore.QRect(10, 400, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.buttonVeriCokla.setFont(font)
        self.buttonVeriCokla.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonVeriCokla.setObjectName("buttonVeriCokla")
        self.cbEarlyStopping = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.cbEarlyStopping.setGeometry(QtCore.QRect(10, 250, 91, 31))
        self.cbEarlyStopping.setObjectName("cbEarlyStopping")
        self.cbModelCheckpoint = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.cbModelCheckpoint.setGeometry(QtCore.QRect(100, 250, 111, 31))
        self.cbModelCheckpoint.setObjectName("cbModelCheckpoint")
        self.txtEpochSayisi = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtEpochSayisi.setGeometry(QtCore.QRect(10, 280, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        self.txtEpochSayisi.setFont(font)
        self.txtEpochSayisi.setInputMask("")
        self.txtEpochSayisi.setText("")
        self.txtEpochSayisi.setObjectName("txtEpochSayisi")
        self.txtBatchSize = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtBatchSize.setGeometry(QtCore.QRect(10, 320, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        self.txtBatchSize.setFont(font)
        self.txtBatchSize.setInputMask("")
        self.txtBatchSize.setText("")
        self.txtBatchSize.setObjectName("txtBatchSize")
        self.btnTespit = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnTespit.setGeometry(QtCore.QRect(10, 520, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnTespit.setFont(font)
        self.btnTespit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnTespit.setObjectName("btnTespit")
        self.buttonCM = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.buttonCM.setGeometry(QtCore.QRect(10, 480, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.buttonCM.setFont(font)
        self.buttonCM.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonCM.setObjectName("buttonCM")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.Veriseti_Yukle = QtWidgets.QPushButton(self.centralwidget)
        self.Veriseti_Yukle.setGeometry(QtCore.QRect(10, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Veriseti_Yukle.setFont(font)
        self.Veriseti_Yukle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Veriseti_Yukle.setObjectName("Veriseti_Yukle")
        self.ResimSec = QtWidgets.QPushButton(self.centralwidget)
        self.ResimSec.setGeometry(QtCore.QRect(170, 10, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ResimSec.setFont(font)
        self.ResimSec.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ResimSec.setObjectName("ResimSec")
        self.h5Sec = QtWidgets.QPushButton(self.centralwidget)
        self.h5Sec.setGeometry(QtCore.QRect(350, 10, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.h5Sec.setFont(font)
        self.h5Sec.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.h5Sec.setObjectName("h5Sec")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 521, 271))
        self.listWidget.setObjectName("listWidget")
        self.imageBox = QtWidgets.QLabel(self.centralwidget)
        self.imageBox.setGeometry(QtCore.QRect(30, 320, 251, 181))
        self.imageBox.setText("")
        self.imageBox.setScaledContents(True)
        self.imageBox.setObjectName("imageBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setText(_translate("MainWindow", "İŞLEM SEÇİNİZ"))
        self.buttonAccuracy.setText(_translate("MainWindow", "Accuracy"))
        self.buttonLoss.setText(_translate("MainWindow", "Loss"))
        self.comboBoxSinif.setCurrentText(_translate("MainWindow", "Sınıflandırıcı seç"))
        self.comboBoxSinif.setItemText(0, _translate("MainWindow", "Sınıflandırıcı seç"))
        self.comboBoxSinif.setItemText(1, _translate("MainWindow", "K-Neighbours"))
        self.comboBoxSinif.setItemText(2, _translate("MainWindow", "Logistic Regression"))
        self.comboBoxSinif.setItemText(3, _translate("MainWindow", "SVM"))
        self.comboBoxModelSec.setCurrentText(_translate("MainWindow", "Model Seç"))
        self.comboBoxModelSec.setItemText(0, _translate("MainWindow", "Model Seç"))
        self.comboBoxModelSec.setItemText(1, _translate("MainWindow", "ResnetB4"))
        self.comboBoxModelSec.setItemText(2, _translate("MainWindow", "EfficientNetB5"))
        self.comboBoxModelSec.setItemText(3, _translate("MainWindow", "VGG16"))
        self.comboBoxModelSec.setItemText(4, _translate("MainWindow", "Our Model"))
        self.comboBoxKFold.setCurrentText(_translate("MainWindow", "K-Fold seçiniz"))
        self.comboBoxKFold.setItemText(0, _translate("MainWindow", "K-Fold seçiniz"))
        self.comboBoxKFold.setItemText(1, _translate("MainWindow", "3"))
        self.comboBoxKFold.setItemText(2, _translate("MainWindow", "5"))
        self.comboBoxKFold.setItemText(3, _translate("MainWindow", "10"))
        self.buttonSinifCalistir.setText(_translate("MainWindow", "Çalıştır"))
        self.buttonModelEgit.setText(_translate("MainWindow", "Model Eğit"))
        self.buttonKFoldUygula.setText(_translate("MainWindow", "Uygula"))
        self.buttonVeriCokla.setText(_translate("MainWindow", "Veri Çoklama"))
        self.cbEarlyStopping.setText(_translate("MainWindow", "Early Stopping"))
        self.cbModelCheckpoint.setText(_translate("MainWindow", "Model Checkpoint"))
        self.txtEpochSayisi.setPlaceholderText(_translate("MainWindow", "Epoch Sayısı Girin"))
        self.txtBatchSize.setPlaceholderText(_translate("MainWindow", "Batch Size Sayısı Girin"))
        self.btnTespit.setText(_translate("MainWindow", "Resim Tespiti"))
        self.buttonCM.setText(_translate("MainWindow", "Confusion Matrix"))
        self.Veriseti_Yukle.setText(_translate("MainWindow", "Veriseti Yükle"))
        self.ResimSec.setText(_translate("MainWindow", "Resim seç"))
        self.h5Sec.setText(_translate("MainWindow", "h5 dosyası sec"))
